### ISSUE TITLE
[AUTH] Login redirecting to error on invalid credentials

### ISSUE THREAD

**Issue by CyberEzpertz** [CyberEzpertz/top-lines-inventory#34]
**Describe the bug**
Login Page redirect to error page when credentials are invalid.

**Steps to Reproduce**
1. Go to "/auth/signIn"
2. Type invalid values for email and password
3. Click the Log In button

**Expected behavior**
Error should appear on the login page itself, and should not redirect to error page.

**Comment by HansSorongon** [comment]
OLEG
