### ISSUE TITLE
[INVENTORY] Duplicate Products Can Be Added with Identical Information in Add Product Batch

### ISSUE THREAD

**Issue by spyhard12** [CyberEzpertz/top-lines-inventory#70]
**Describe the bug**
When adding products, users can submit multiple entries with identical information (product code, brand name, product name, lot number, quantity, purchase price, expiration date, retail price). These duplicates also coexist in the data table without any distinguishing information.

**Steps to Reproduce**
1. Login
2. Go to '/Inventory'
3. Click on 'Add'
4. Click on 'New Product'
5. Enter "TestCode" as 'Product Code'
6. Enter "TestBrand" as 'Brand Name'
7. Enter "TestName" as 'Product Name'
8. Enter "ALTEST" as 'Lot No.'
9. Enter "10" as "Quantity"
10. Enter "50" as 'Purchase Price'
11. Enter "50" as 'Retail Price'
12. Chose "November 6th, 2024" as 'Expiration Date'
13. Click on 'Submit'
14. Redo steps 3 to 13
15. Click on 'Updated At' header
16. Click on 'Desc'
17. See duplicate entries

**Expected behavior**
The system should prevent the addition of products with identical information or provide distinguishing information for them shown on the data table or choosers where products are options

**Actual behavior**
The system allows users to add multiple products with identical information with no distinguishing information shown in the data table or dropdowns they are seen in

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/0fee9b2e-bcc2-48dc-a073-434d144c571f)
![image](https://github.com/user-attachments/assets/d346cb5e-bd64-4d9f-a703-45d2fa3b0265)
![image](https://github.com/user-attachments/assets/e1484b99-cd14-4557-9a75-cefbe87c7a75)

**Additional context (optional)**
These duplicates are also seen in the dropdown of existing products in add product batch, and in adding sales invoice for choosing a product

**Comment by CyberEzpertz** [comment]
@spyhard12 fix has been implemented in PR #74 , will close this now. Re-open this if issue still persists.
